R2Northstar/Northstar

.github/ISSUE_TEMPLATE.md

Maybe this way we finally get more logs and screenshots ¯\\\_(ツ)\_/¯

Mention drag-and-dropping

---

.github/workflows/build.yml

updates R2Northstar/NorthstarLauncher#79

Include NorthstarStubs in releases

---

.github/workflows/build.yml

Sets hardcoded version number defined in https://github.com/R2Northstar/NorthstarLauncher/pull/152 in CI on release build.

Set hardcoded version number on release build

---

README.md

Add badge for downloads of current version

---

release/LEGAL.txt

Related PRs:
https://github.com/R2Northstar/NorthstarMods/pull/437
https://github.com/R2Northstar/NorthstarWiki/pull/91

Add licenses for Northstar Mono (Fira Mono Derivative) and Lato fonts

---

.github/workflows/build.yml

Some directories got changed as part of refactor

Update paths in CI config

---

README.md

Add NorthstarNavs link to README

---

.github/workflows/build.yml

This allows for explicit updates of NorthstarNavs and more reproducible builds.
Closes #364

Use tagged version of Navmeshes

---

.github/workflows/build.yml

Update DiscordRPC to v4

---

.github/workflows/build.yml

Fix typo in 7a7ca84bd2160263143d09a959d3e2cce106efd0 (#461)

---

README.md

Update README project list to mention Atlas, DiscordRPC, and webpage as well.

Update README project list

---

.github/workflows/add-to-project.yml

Automatically adds all opened issues and pull requests to the project board.

Add workflow for adding PRs and Issues to the project board

---

.github/workflows/add-to-project.yml

works on the other repos (launcher and mods) so yeah

Make add-to-project work on PRs

---

.github/workflows/build.yml

Delete bash scripts in project root as well to prevent wait script from being included in release files.
fixes

Delete bash scripts in project root as well

---

.github/workflows/build.yml

Makes it easier to copy out for making PR to Docker image repo
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

Print checksum to job summary

---

.github/workflows/build.yml

Calculate checksum twice instead of storing result in env var.
For some reason storing result in var didn't work and I don't know why nor am I in the mood of investigating it :P

Calculate checksum twice

---

.github/workflows/release.yml

Rename `Build` Action to `Release` to better reflect what it does

Rename Action from `Build` to `Release`

---

.github/workflows/release.yml

Updates Navs to v3 which includes this update https://github.com/R2Northstar/NorthstarNavs/pull/6
cc @taskinoz @Zanieon

Bump NorthstarNavs to v3

---

.github/workflows/release.yml

Bumps DiscordRPC to match _Plugin Interfaces_ / _Plugins v4_.

Bump DiscordRPC to v9

---

.github/workflows/post-to-mastodon.yml

And update parameters accordingly

Bump `cbrgm/mastodon-github-action` to v2

---

.github/workflows/release.yml

Updates Navs to v4 which includes this update https://github.com/R2Northstar/NorthstarNavs/pull/7

 Bump NorthstarNavs to v4

---

.github/workflows/release.yml

Adds https://github.com/R2Northstar/NorthstarDiscordRPC/pull/22

Bump DiscordRPC plugin to v11

---

.github/workflows/release.yml

Adds https://github.com/R2Northstar/NorthstarDiscordRPC/pull/25

Bump DiscordRPC plugin to v12

---

.github/workflows/release.yml

Adds https://github.com/R2Northstar/NorthstarDiscordRPC/pull/26

Bump DiscordRPC plugin to v13
