R2Northstar/Northstar

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
Currently, all issues are being opened on main repo, which does not grant a great visibility; ideally, there would be no `bugs` channel on Discord server, and all issues would be created in concerned repos.
Please don't hesitate to comment and add your ideas on this PR.
Adding some contributing documentation.
Adressing https://github.com/R2Northstar/Northstar/issues/55.
---
* feature
* bug
* suggestion
* priority-1
* priority-2
* priority-3
* priority-4
* priority-5
* server
* client
* updater
* UI
* authentication
> Development organization

- .github/workflows/build.yml
This is an interim fix for the library load error messagebox when the Discord app is not being used.
> Include Discord SDK in launcher builds

- .github/workflows/build.yml
Previously the digit of the rc as well as the dash would remain
E.g.: `-rc2` -> `-2`
This resulted in it being subtracted from the patch version digit
E.g.: `v1.7.0-rc1` turns into `1,7,0-1`.
This PR strips the whole `-rcX` part of the version number in CI
Closes #265
> Strip `-rcX` suffix from version number properly

- .github/workflows/build.yml
Publishes release-candidates to Thunderstore under `NorthstarReleaseCandidate`
As Thunderstore doesn't support extended semver, release candidate number for Thunderstore is changed as follows: `v1.9.1-rc2` -> `v1.9.102`
> Publish release-candidates to Thunderstore

- .github/workflows/build.yml
Basically just a small safeguard to prevent running CI on accidentally pushed invalid tag.
> Enforce tags start with `v` for CI to run

- .github/workflows/build.yml
- release/ns_startup_args.txt
- release/ns_startup_args_dedi.txt
Deletes `ns_startup_args.txt` and `ns_startup_args_dedi.txt`.
As per https://github.com/R2Northstar/NorthstarLauncher/pull/99 we no longer need them. NorthstarLauncher should just auto-create them when missing.
> Delete startup args txt files

- .github/workflows/build.yml
Resolves issue with rc version number not having leading zeroes stripped
> Fix regex breaking on multi-digit version numbers

- .github/workflows/build.yml
Version bump as v2 used NodeJS 12 which is being deprecated on runners.
> Update actions to newest version

- .github/workflows/build.yml
This way builds are more reproducible as specific versions of NorthstarDiscordRPC can be set, meaning updating NorthstarDiscordRPC to newer plugin API won't immediately break CI runs of older Northstar release builds.
Closes #352
> Use tagged version of DiscordRPC

- .github/workflows/build.yml
Uses https://github.com/softprops/action-gh-release to create a draft release and upload the Northstar release zip to it.
I adapted the example [found here](https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets) for Northstar.
Not tested cause not sure how I'd do it with [act](https://github.com/nektos/act) without modifying releases on this repo...
> Add step to create release draft and upload zip

- .github/workflows/build.yml
Instead of re-compiling on each release, simply grab the precompiled DiscordRPC DLLs.
Shaves off around 1 minute of build time.
Sample run: https://github.com/GeckoEidechse/Temp-Northstar/actions/runs/4407266520
(Upload to Thunderstore is expected to fail on fork due to missing access key)
> Grab pre-compiled DiscordRPC plugin

- .github/workflows/build.yml
To address a warning currently shown when running the checkout action:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/download-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Bump download-artifact action to v3

- .github/workflows/build.yml
This will make it faster to update the Docker image.
> Show SHA-512 checksum of release zip

- .github/workflows/build.yml
For some reason there's a stray empty `release` folder inside the release zip that shouldn't be there.
> Remove stray release dir from release zip

- .github/workflows/build.yml
Fetches launcher build from latest release on NorthstarLauncher
NOTE: Due to the differences between old build system and cmake for the files to be structured properly a release on NorthstarLauncher needs to be made.
Closes #497
> Download launcher from release instead of rebuilding

- .github/workflows/post-to-mastodon.yml
This PR adds an action that publishes a new Mastodon post linking to the newest release when it is released.
Posts are sent from https://fosstodon.org/@R2Northstar
Uses https://github.com/cbrgm/mastodon-github-action/
> Publish Mastodon post on new release

- .github/workflows/build.yml
Checkout the files from this repo first in order to have the bash script ready that is needed to block launcher files download.
> Checkout repo files as first step

- .github/workflows/build.yml
Bump DiscordRPC plugin to v5 which corresponds to the first version that supports plugins v3.
See also:
- https://github.com/R2Northstar/NorthstarDiscordRPC/pull/10
- https://github.com/R2Northstar/NorthstarMods/pull/652
- https://github.com/R2Northstar/NorthstarLauncher/pull/472
> Bump DiscordRPC plugin to v5

- .github/workflows/build.yml
Bumps DiscordRPC to v6 which switches the `rrplug` dependency from a git repo to the appropriate release on crates.io
> Bump DiscordRPC plugin to v6

- .github/workflows/release.yml
Escape backticks in run command as otherwise bash thinks we're trying to run the command "`"
> Escape backticks in run command

- .github/workflows/release.yml
v3 uses Node 16 which is slated for deprecation by GitHub Actions
> Bump actions/checkout to v4

- .github/workflows/release.yml
Bump runner to from Ubuntu 20.04 to 22.04.
Bumps it to the currently latest LTS Ubuntu runner. I'm still manually specifying runner version over `latest` to avoid any potential breakage on new release.
> Bump CI runner to Ubuntu 22.04

- .github/workflows/release.yml
Bump upload/download artifact actions to v4 as v3 is being deprecated in a few months
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Bump upload/download artifact actions to v4

- .github/workflows/release.yml
Bump `softprops/action-gh-release` action to v2 as v1 uses Node 16 which is being deprecated in a few months
> Bump softprops/action-gh-release action to v2

- .github/workflows/release.yml
Just adds https://github.com/R2Northstar/NorthstarDiscordRPC/pull/24 which bumps `rrplug` to `4.0.0`.
> Bump DiscordRPC plugin to v10

- .github/workflows/merge-conflict-auto-label.yml
Adds an action that on every push to main and periodically checks open PRs for merge conflicts and adds/removes labels on them accordingly.
> Add Action to auto-label PRs with merge conflicts

- .github/workflows/release.yml
We currently add the `README.md` for NorthstarMods into release zip but there's no reason for it to be there.
> Exclude markdown files from Mods in releases

- .github/workflows/release.yml
Use long arg for `tr` command as it's more readable
> Use long arg for `tr` command

- .github/workflows/release.yml
Use env var to define DiscordRPC version to make editing the version number easier
> Use env var to define DiscordRPC version
